### ISSUE TITLE
Failed to start the app in AWS Beanstalk - AttributeError: module '__main__' has no attribute 'tokenize'

### ISSUE THREAD

**Issue by ocinpp** [ocinpp/data-scientist-disaster-response-pipeline#1]
[Wed Dec 19 16:54:48.112848 2018] [:error] [pid 16844] [remote 71.6.142.85:192] mod_wsgi (pid=16844): Target WSGI script '/opt/python/current/app/app/run.py' cannot be loaded as Python module.
[Wed Dec 19 16:54:48.112907 2018] [:error] [pid 16844] [remote 71.6.142.85:192] mod_wsgi (pid=16844): Exception occurred processing WSGI script '/opt/python/current/app/app/run.py'.
[Wed Dec 19 16:54:48.113043 2018] [:error] [pid 16844] [remote 71.6.142.85:192] Traceback (most recent call last):
[Wed Dec 19 16:54:48.113084 2018] [:error] [pid 16844] [remote 71.6.142.85:192]   File "/opt/python/current/app/app/run.py", line 43, in <module>
[Wed Dec 19 16:54:48.113088 2018] [:error] [pid 16844] [remote 71.6.142.85:192]     model = joblib.load("models/classifier.pkl")
[Wed Dec 19 16:54:48.113121 2018] [:error] [pid 16844] [remote 71.6.142.85:192]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 578, in load
[Wed Dec 19 16:54:48.113127 2018] [:error] [pid 16844] [remote 71.6.142.85:192]     obj = _unpickle(fobj, filename, mmap_mode)
[Wed Dec 19 16:54:48.113134 2018] [:error] [pid 16844] [remote 71.6.142.85:192]   File "/opt/python/run/venv/local/lib64/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 508, in _unpickle
[Wed Dec 19 16:54:48.113137 2018] [:error] [pid 16844] [remote 71.6.142.85:192]     obj = unpickler.load()
[Wed Dec 19 16:54:48.113142 2018] [:error] [pid 16844] [remote 71.6.142.85:192]   File "/usr/lib64/python3.6/pickle.py", line 1050, in load
[Wed Dec 19 16:54:48.113144 2018] [:error] [pid 16844] [remote 71.6.142.85:192]     dispatch[key[0]](self)
[Wed Dec 19 16:54:48.113149 2018] [:error] [pid 16844] [remote 71.6.142.85:192]   File "/usr/lib64/python3.6/pickle.py", line 1338, in load_global
[Wed Dec 19 16:54:48.113152 2018] [:error] [pid 16844] [remote 71.6.142.85:192]     klass = self.find_class(module, name)
[Wed Dec 19 16:54:48.113156 2018] [:error] [pid 16844] [remote 71.6.142.85:192]   File "/usr/lib64/python3.6/pickle.py", line 1392, in find_class
[Wed Dec 19 16:54:48.113159 2018] [:error] [pid 16844] [remote 71.6.142.85:192]     return getattr(sys.modules[module], name)
[Wed Dec 19 16:54:48.113174 2018] [:error] [pid 16844] [remote 71.6.142.85:192] AttributeError: module '__main__' has no attribute 'tokenize'

**Comment by ocinpp** [comment]
Fixed in #2
